"""Initial migration

Revision ID: 27cb8316c423
Revises: 
Create Date: 2025-07-11 01:15:57.115427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cb8316c423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False, comment='unique identifier for the collection'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='name of the collection'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='description of the collection'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='timestamp when the collection was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='timestamp when the collection was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False, comment='unique identifier for the file'),
    sa.Column('filename', sa.String(length=80), nullable=False, comment='original name of the file'),
    sa.Column('filesize', sa.Integer(), nullable=False, comment='size of the file in bytes'),
    sa.Column('content_type', sa.String(length=30), nullable=False, comment='MIME type of the file'),
    sa.Column('path', sa.String(), nullable=False, comment='path where the file is stored on disk or cloud storage'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='timestamp when the file was created'),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('collections')
    # ### end Alembic commands ###
