"""add embedding column for collection

Revision ID: 5adcefb35836
Revises: 27cb8316c423
Create Date: 2025-07-14 21:16:49.482759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adcefb35836'
down_revision: Union[str, Sequence[str], None] = '27cb8316c423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('embedding_model', sa.String(length=50), nullable=False, comment='embedding model used for the collection'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'embedding_model')
    # ### end Alembic commands ###
