"""rename size column and remove unique constraint in files

Revision ID: 6e0b34497913
Revises: feaec9591d9b
Create Date: 2025-07-21 09:06:21.659252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e0b34497913"
down_revision: Union[str, Sequence[str], None] = "feaec9591d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "filesize", new_column_name="size")
    op.drop_constraint(op.f("files_filename_key"), "files", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "filesize",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="size of the file in bytes",
        ),
    )
    op.create_unique_constraint(
        op.f("files_filename_key"),
        "files",
        ["filename"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("files", "size")
    # ### end Alembic commands ###
