"""add status in file

Revision ID: bdea55b2fffc
Revises: 6e0b34497913
Create Date: 2025-07-24 10:14:43.687948

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bdea55b2fffc"
down_revision: Union[str, Sequence[str], None] = "6e0b34497913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "status",
            postgresql.ENUM(
                "UPLOADED",
                "CHUNKED",
                "CHUNK_FAILED",
                "EMBEDDING",
                "EMBEDDING_PARTIAL_FAILED",
                "SUCCESS",
                "FAILED",
                name="filestatus",
            ),
            nullable=False,
            comment="current processing status of the file",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "status")
    # ### end Alembic commands ###
