"""add embedding related columns for column

Revision ID: feaec9591d9b
Revises: 5adcefb35836
Create Date: 2025-07-19 12:03:20.447993

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "feaec9591d9b"
down_revision: Union[str, Sequence[str], None] = "5adcefb35836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    op.add_column(
        "collections",
        sa.Column(
            "embedding_model_provider",
            sa.String(length=20),
            nullable=False,
            comment="embedding provider used for the collection",
        ),
    )
    op.add_column(
        "collections",
        sa.Column(
            "embedding_model_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="metadata for the embedding model used in the collection",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "embedding_model_metadata")
    op.drop_column("collections", "embedding_model_provider")
    # ### end Alembic commands ###
